In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

using numpy to create a 2D array of shape (3,3)

In [12]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# multiplying each element by 2 and storing it in y
y = x * 2

In [16]:
y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# creating a dataframe using pandas from a dictionary, with columns product_name, price, quantity
data = {
    'product_name': ['Bottle', 'Plates', 'AC', 'Fan'],
    'price': [50, 150, 80000, 2500],
    'quantity': [450, 200, 25, 70]
}
df = pd.DataFrame(data)

In [23]:
# data filtering to find the products with  stock_quantity greater than 50
filtered_df = df[df['quantity'] > 50]
filtered_df

product_name  price  quantity
0       Bottle     50       450
1       Plates    150       200
3          Fan   2500        70