In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Functions

#### Function definition

In [7]:
def student_info(name, age =18):
    print(name, age)

#### Function calling

In [9]:

student_info("Piyush", 22)

Piyush 22


### Numpy 

##### Install commands

In [ ]:
pip install numpy

##### importing

In [ ]:
import numpy as np

#### Arrays in Numpy

In [11]:
x=np.array([1,2,3,4,5])

In [12]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [15]:
print('x =',x)
print('y =',y)
print('z =',z)

x = [1 2 3 4 5]
y = [[1 2 3]
 [4 5 6]
 [7 8 9]]
z = [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


## Pandas

##### Use cases

Converting Data into series and data frame

In [16]:
s = pd.Series([1,3,5,np.nan,6,8])

In [17]:
name = ['Piyush', 'Aman', 'Rohit', 'Suman', 'Ankit']
age = [22, 21, 23, 22, 24]

In [18]:
print(f"Pandas Series:\n{s}\n")
print(f"Types of Series:{type(s)}")

Pandas Series:
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Types of Series:<class 'pandas.core.series.Series'>


In [20]:
data={
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 60000, 90000, 75000],
}

In [22]:
df = pd.DataFrame(data)
print(data)
print(f"\nPandas DataFrame:\n{df}")

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'], 'Age': [24, 27, 22, 32, 29], 'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 'Salary': [70000, 80000, 60000, 90000, 75000]}

Pandas DataFrame:
      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   60000
3    David   32      Houston   90000
4      Eva   29      Phoenix   75000


In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/MainakRepositor/Datasets/refs/heads/master/TV_Shows.csv')

In [28]:
df.head()

Unnamed: 0             Title  Year  Age  IMDb Rotten Tomatoes  Netflix  \
0           0      Breaking Bad  2008  18+   9.5             96%        1   
1           1   Stranger Things  2016  16+   8.8             93%        1   
2           2       Money Heist  2017  18+   8.4             91%        1   
3           3          Sherlock  2010  16+   9.1             78%        1   
4           4  Better Call Saul  2015  18+   8.7             97%        1   

   Hulu  Prime Video  Disney+  type  
0     0            0        0     1  
1     0            0        0     1  
2     0            0        0     1  
3     0            0        0     1  
4     0            0        0     1

In [29]:
df

Unnamed: 0                            Title  Year  Age  IMDb  \
0              0                     Breaking Bad  2008  18+   9.5   
1              1                  Stranger Things  2016  16+   8.8   
2              2                      Money Heist  2017  18+   8.4   
3              3                         Sherlock  2010  16+   9.1   
4              4                 Better Call Saul  2015  18+   8.7   
...          ...                              ...   ...  ...   ...   
5606        5606  Tut's Treasures: Hidden Secrets  2018  NaN   NaN   
5607        5607                 Paradise Islands  2017  NaN   NaN   
5608        5608                      Wild Russia  2018  NaN   NaN   
5609        5609                      Love & Vets  2017  NaN   NaN   
5610        5610         United States of Animals  2016  NaN   NaN   

     Rotten Tomatoes  Netflix  Hulu  Prime Video  Disney+  type  
0                96%        1     0            0        0     1  
1                93%        1     0            0        0     1  
2                91%        1     0            0        0     1  
3                78%        1     0            0        0     1  
4                97%        1     0            0        0     1  
...              ...      ...   ...          ...      ...   ...  
5606             NaN        0     0            0        1     1  
5607             NaN        0     0            0        1     1  
5608             NaN        0     0            0        1     1  
5609             NaN        0     0            0        1     1  
5610             NaN        0     0            0        1     1  

[5611 rows x 11 columns]

In [32]:
df = pd.read_csv('TV_Shows.csv')

In [33]:
df.head()

Unnamed: 0             Title  Year  Age  IMDb Rotten Tomatoes  Netflix  \
0           0      Breaking Bad  2008  18+   9.5             96%        1   
1           1   Stranger Things  2016  16+   8.8             93%        1   
2           2       Money Heist  2017  18+   8.4             91%        1   
3           3          Sherlock  2010  16+   9.1             78%        1   
4           4  Better Call Saul  2015  18+   8.7             97%        1   

   Hulu  Prime Video  Disney+  type  
0     0            0        0     1  
1     0            0        0     1  
2     0            0        0     1  
3     0            0        0     1  
4     0            0        0     1